#ifndef KBD_MAP_H
#define KBD_MAP_H

/* store all mappings from keyboard keys to opcodes */

#define KBD_PORT 0x60
#define TABSIZE 4

#define LSHIFT_RELEASE 0xAA
#define RSHIFT_RELEASE 0xB6
#define BACKSPACE_PRESSED 0x0E
#define BACKSPACE_RELEASE 0x8E
#define TAB_PRESSED 0x0F
#define TAB_RELEASE 0x8F
#define ENTER_PRESSED 0x1C
#define ENTER_RELEASE 0x9C
#define F12_BOUNDS 0x58
#define CAPSLOCK_PRESSED 0x3A
#define LEFTSHIFT_PRESSED 0x2A
#define RIGHTSHIFT_PRESSED 0x36
#define L_PRESS 0x26
#define C_PRESS 0x2E
#define LEFTALT_PRESSED 0x38
#define LEFTCTRL_PRESSED 0x1D
#define LEFTALT_RELEASE 0xB8
#define LEFTCTRL_RELEASE 0x9D
#define CAPSLOCK_RELEASE 0xBA
#define ESCAPE_PRESSED 0x01
#define F1_PRESSED 0x3B
#define F2_PRESSED 0x3C
#define KEYPADMULT_PRESSED 0x37
#define F3_PRESSED 0x3D
#define F4_PRESSED 0x3E
#define F5_PRESSED 0x3F
#define F6_PRESSED 0x40
#define F7_PRESSED 0x41
#define F8_PRESSED 0x42
#define F9_PRESSED 0x43
#define F10_PRESSED 0x44
#define NUMLOCK_PRESSED 0x45
#define SCROLLLOCK_PRESSED 0x46
#define KEYPAD7_PRESSED 0x47
#define KEYPAD8_PRESSED 0x48
#define KEYPAD9_PRESSED 0x49
#define KEYPADMINUS_PRESSED 0x4A
#define KEYPAD4_PRESSED 0x4B
#define KEYPAD5_PRESSED 0x4C
#define KEYPAD6_PRESSED 0x4D
#define KEYPADPLUS_PRESSED 0x4E
#define KEYPAD1_PRESSED 0x4F
#define KEYPAD2_PRESSED 0x50
#define KEYPAD3_PRESSED 0x51
#define KEYPAD0_PRESSED 0x52
#define KEYPADPERIOD_PRESSED 0x53
#define F11_PRESSED 0x57
#define F12_PRESSED 0x58
#define BACKTICK_PRESSED 0x29
#define ONE_PRESSED 0x02
#define TWO_PRESSED 0x03
#define THREE_PRESSED 0x04
#define FOUR_PRESSED 0x05
#define FIVE_PRESSED 0x06
#define SIX_PRESSED 0x07
#define SEVEN_PRESSED 0x08
#define EIGHT_PRESSED 0x09
#define NINE_PRESSED 0x0A
#define ZERO_PRESSED 0x0B
#define MINUS_PRESSED 0x0C
#define EQUAL_PRESSED 0x0D
#define LEFTBRACKET_PRESSED 0x1A
#define RIGHTBRACKET_PRESSED 0x1B
#define BACKSLASH_PRESSED 0x2B
#define SEMICOLON_PRESSED 0x27
#define SINGLEQUOTE_PRESSED 0x28
#define COMMA_PRESSED 0x33
#define PERIOD_PRESSED 0x34
#define FORWARDSLASH_PRESSED 0x35

#endif	/* endif KBD_MAP_H */
